spring:
  application:
    name: instagrat
  ai:
    mistralai:
      apiKey:
      model: open-mistral-7b
    vectorstore:
      pinecone:
        apiKey:
        environment:
        projectId:
        indexName:

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: instagrat
